{{- if .Values.indexIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
  {{- with .Values.indexIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ first .Values.indexIngress.hosts }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "graphprotocol-node.fullname" $ }}
                port:
                  name: json-rpc
    - host: {{ first .Values.indexIngress.ipfs.hosts }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ipfs-ipfs
                port:
                  name: api
{{- end }}
---
{{- if .Values.indexIngress.enabled -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}-cert
spec:
  domains:
    - {{ first .Values.indexIngress.hosts }}
    - {{ first .Values.indexIngress.ipfs.hosts }}
{{- end }}