# Email that would be used during issuing https certs. It would be used by let's encrypt to notify about expiring certs.
email: info@ainur.dev

postgresDatasource:
  url: postgres-postgres.graph:5432 # Postgres host, format postgres-postgres.<graph-node namespace>:5432
  user: node
  db: node
  password: PjxFqltEYEU4IC6lqfCEBbt9UXKY2Ew4ilaUyk5waC6tGFn2i8WoQhfebJalzlaG

# Enables infra components
ingressNginx:
  enabled: false
caddy:
  enabled: true
postgresOperator:
  enabled: true
certManager:
  enabled: false
letsencryptProdIssuer:
  enabled: false
kubernetesDashboard:
  enabled: false
kubernetesDashboardSA:
  enabled: false
prometheusStack:
  enabled: true
graphGrafanaDashboards:
  enabled: true
