resources:
  requests:
    cpu: "0.5"
    memory: 0.5Gi
  limits:
    cpu: "1"
    memory: 1Gi

numberOfInstances: 1

postgresql:
  version: "15"
  parameters:  # Expert section
    shared_buffers: "1GB"
    max_connections: "500"

volume:
  size: 150Gi
